### ISSUE TITLE
[REQUEST FOR COMMENT] Documentation meta-issue

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1319]
Before releasing `3.11`, I'd like to improve the documentation.

Here are the major blocks I have in mind:

- [ ] Core concepts. An intuitive-level explanation of what Schemathesis is and what problems it solves. The main goal of this block is to build a high-level understanding of the project in the end-user's mind. E.g. what one might expect from Schemathesis, how many tests it generates and why etc.
- [ ] Advanced details. This is a more detailed explanation of individual parameters and how they affect the testing process
- [ ] How it works. If somebody is curious about how it works internally, this is the place to check. It should also cover the design decisions and the reasoning around them. A high-level architecture structure is also here.

Anybody reading this issue, feel free to add a topic you'd like to see covered in this upcoming docs update.
