### ISSUE TITLE
Refactoring meta-issue

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#688]
Over time it became harder to implement certain features and I'd like to focus on refactoring and various improvements to the codebase for some time.

The major problem I want to solve is GraphQL integration - currently, it is quite hacky, and implementing pytest & CLI support without hacks requires some major changes in the Schemathesis structure.

Here are the directions that could be taken in order to move faster with GraphQL:

- [ ] Replace `GenericResponse` with a common abstraction. There are multiple conditions scattered across the codebase that check if a variable with that type is one or another option. A common abstraction will isolate this code in one place;
- [ ] Make `Endpoint` model more generic. For GraphQL some parts should be adjusted - `as_strategy` should use `hypothesis_graphql` under the hood, `definition` attribute should not be bound to Open API, etc.
- [ ] `Case` is used everywhere, but for GraphQL there is a different class. Protocols could be used instead to avoid inheritance
- [ ] `endpoint` might be a misleading term - for GraphQL there is only "query", need to think about it.
- [ ]  `parametrize` accepts keywords, that don't make sense for GraphQL - it should be done differently in this case. They are also stored on a `BaseSchema` instance, which doesn't seem right

As the final result, I'd like to see CLI, runner and pytest integration that will not be tied to Open API specific structures, but will rather work with ones that will be generic and probably will delegate spec-specific logic to their internal components, i.e. will use composition approach.

As a side-note: Not everything should be tight to that `BaseSchema` subclasses - probably it could be just some "dispatch"-like functions, not sure yet
